### ISSUE TITLE
UnboundLocalError;What  can I do?

### ISSUE THREAD

**Issue by ysuzalmon** [Heumi/BEGAN-tensorflow#2]
File "main.py", line 56, in <module>
    main()
  File "main.py", line 51, in main
    model.train(args.flag)
UnboundLocalError: local variable 'model' referenced before assignment

**Comment by hmi88** [comment]
Do you use dropbox file? If you use that file, you need to add __init__.py

**Comment by ysuzalmon** [comment]
I do not use the dropbox file.
Run :  python main.py -f 1 -p "began" -trd "celeba" -tro "crop" -trs 64  -z 128 -em 128 -fn 64  -b 16 -lr 1e-4 -gm 0.4 -g "0"

**Comment by MichaelOVertolli** [comment]
There's an underscore in the if statement `"began_"` which should be removed (and is removed in the dropbox file).

**Comment by ysuzalmon** [comment]
Thank you very much!
